# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
test_bmi_calculator: Simple BMI calculator
Generated by ADK Agent Generator
"""

from google.adk.agents.llm_agent import LlmAgent
from google.adk.agents.loop_agent import LoopAgent
from google.adk.agents.parallel_agent import ParallelAgent
from google.adk.agents.sequential_agent import SequentialAgent
from google.adk.tools.function_tool import FunctionTool
from google.genai import types




# Calculates BMI
bmi_agent = LlmAgent(
    name="bmi_agent",
    model="gemini-pro",
    description="""
    Calculates BMI
    """,
    instruction="""
    You calculate BMI from weight and height.
    """
)


# Main agent (entry point)
root_agent = bmi_agent
